/* pre-compiled include files for fmain.c */

#include "exec/types.h"
#include "exec/memory.h"
#include "graphics/view.h"
#include "hardware/blit.h"
#include "hardware/custom.h"
#include "graphics/gfxmacros.h"
#include "graphics/copper.h"
#include "graphics/display.h"
#include "graphics/text.h"
#include "graphics/gfxbase.h"
#include "graphics/sprite.h"
#include "exec/devices.h"
#include "libraries/diskfont.h"
#include "libraries/dosextens.h"
#include "devices/audio.h"
#include "devices/input.h"
#include "devices/inputevent.h"
#include "devices/trackdisk.h"
#include "workbench/startup.h"

#include "clib/alib_protos.h"
#include "clib/exec_protos.h"
#include "clib/graphics_protos.h"
#include "clib/layers_protos.h"
#include "clib/dos_protos.h"
#include "clib/intuition_protos.h"
#include "clib/diskfont_protos.h"
