/* fmain2.c */
void dohit(register long i, register long j, register long fc, short wt);
void aftermath(void);
int proxcheck(short x, short y, short i);
int nearest_fig(char constraint, short dist);
int calc_dist(register long a, register long b);
int move_figure(short fig, short dir, short dist);
void drawcompass(short dir);
void fade_page(short r, short g, short b, short limit, USHORT *colors);
void colorplay(void);
void ppick(void);
void print(register char *str);
void print_cont(register char *str);
void extract(register char *start);
void announce_container(char *s);
void announce_treasure(char *s);
void name(void);
void map_message(void);
void message_off(void);
void fade_down(void);
void fade_normal(void);
void stillscreen(void);
void shape_read(void);
void read_shapes(register long num);
void seekn(void);
void prep(short slot);
void load_next(void);
void read_score(void);
void copypage(char *br1, char *br2, short x, short y);
void flipscan(void);
int skipint(void);
UBYTE *into_chip(register UBYTE *oldpointer, long size);
void witch_fx(register struct fpage *fp);
void do_objects(void);
void leave_item(short i, short object);
void change_object(register long id, register long flag);
void set_objects(struct object *list, short length, long f);
int copy_protect_junk(void);
int locktest(char *name, long access);
int cpytest(void);
int waitnewdisk(void);
void savegame(short hit);
void saveload(char *buffer, long length);
void move_extent(short e, short x, short y);
void rescue(void);
void win_colors(void);
void day_fade(void);
void do_tactic(register long i, register long tactic);
void eat(int amt);
void set_loc(void);
