/* fmain.c */
int open_all(void);
void close_all(void);
void read_sample(void);
int doorfind(register USHORT x, register USHORT y, register ULONG keytype);
void main(int argc, char argv[]);
void xfer(register USHORT xtest, register USHORT ytest, register USHORT flag);
void find_place(short flag);
void load_actors(void);
void checkdead(register long i, register long dtype);
void load_carrier(short n);
void revive(short new);
void screen_size(register long x);
void setmood(char now);
void gen_mini(void);
void pagechange(void);
int add_device(void);
void wrap_device(void);
void print_options(void);
void propt(short j, short pena);
void do_option(short hit);
void get_turtle(void);
void gomenu(short mode);
void set_options(void);
void load_all(void);
void load_new_region(void);
void effect(short num, long speed);
int set_encounter(USHORT i, USHORT spread);
void mod1save(void);
